[tool.ruff]
line-length = 79

[tool.ruff.format]
quote-style = "preserve"
docstring-code-format = true

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "S", "UP"]

[tool.ruff.lint.per-file-ignores]
"cliff/tests/*" = ["S"]
